language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uchistopat:$BINTRAY_API_KEY "https://api.bintray.com/content/chistopat/otus_cpp_repo/helloworld/0.0.$TRAVIS_BUILD_NUMBER/bin"
    
